# only support English doc
server:
  port: 80

# spring
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test
    username: root
    password: 123

# mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.mybatis.mybatis.domain

# pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true # pageSize<0 = pageSize=0
  support-methods-arguments: true
  params: count=countSql
  pageSizeZero: true