-- auto Generated on 2018-09-13
-- DROP TABLE IF EXISTS teacher;
CREATE TABLE teacher(
	id VARCHAR (50) NOT NULL AUTO_INCREMENT COMMENT 'id',
	name VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'name',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'teacher';
